/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./components/layout/AppLayout.vue')['default']
    ChatInput: typeof import('./components/chat/ChatInput.vue')['default']
    ChatMessageList: typeof import('./components/chat/ChatMessageList.vue')['default']
    ChatSessionList: typeof import('./components/chat/ChatSessionList.vue')['default']
    KbCreateModal: typeof import('./components/kb/KbCreateModal.vue')['default']
    KbSettingsModal: typeof import('./components/kb/KbSettingsModal.vue')['default']
    KbUploadModal: typeof import('./components/kb/KbUploadModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
